### ISSUE TITLE
Witness URL link in wallet is invalid, but has been properly set using 'update_witness'

### ISSUE THREAD

**Issue by sphtxtomjones** [SophiaTX/Wallet-Frontend-issues#3] opened 2018-12-03 15:42 UTC
**Describe the bug**
Witness URL link in wallet is invalid, but has been properly set using 'update_witness'. This is true for the witness 'tomjones' and possibly other witnesses.

**To Reproduce**
1. Go to 'https://wallet.sophiatx.com and login to any user wallet'
2. Click on 'Voting for Witnesses'
3. Scroll down to 'Witness "tomjones"'
4. See error - Hover over link next to witness.

**Expected behavior**
The link included in the update_witness command should be available by clicking on the link icon.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chroms

**Additional context**
Link worked prior to the release of blockchain version 1.1.0.

**Comment by mathudak** [comment] 2018-12-03 17:20
Thanks @sphtxtomjones, the problem was caused by javascript's unique way of handling regex expression flags. It is now fixed and will be deployed in next minor release.

**Comment by mathudak** [comment] 2018-12-05 10:34
Fixed and deployed -> version 1.2.1

**Closed as completed by mathudak** 2018-12-05 10:34 UTC
Labels: status:inProgress, priority:high, type:bug
